config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  resources :messages , only: [:create , :destroy]
  devise_for :users , controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 1000 }

  after_create_commit :broadcast_create
  after_destroy_commit :broadcast_destroy

  def broadcast_create
    broadcast_append_to "messages",
                        partial: "messages/message",
                        locals: { message: self, display_control: false }

    broadcast_replace_to "user_#{self.user.id}",
                         target: "message_#{self.id}_controls",
                         partial: "messages/controls",
                         locals: { message: self }
  end

  def broadcast_destroy
    broadcast_remove_to "messages"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_message, only: [:destroy]

    def create
        message = current_user.messages.build(message_params)
        message.save
    end

    def destroy
        @message.destroy
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end

    def set_message
        @message = Message.find(params[:id])
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :authenticate_user!

  def home
    @messages = Message.last(5)
    @message = current_user.messages.build
    
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_chatbox.html.erb
<%= turbo_stream_from "messages"%>
<div class="h-96 overflow-y-scroll text-textColorMain"
    data-controller="chat"
    data-chat-current-user-id-value="<%=current_user.id%>">
<div id="messages">
    <% @messages.each do |message| %>
        <%= render partial: "messages/message",
        locals: {
            message: message,
            display_control: message.user == current_user
        } %>
    <%end%>
</div>
</div>

app/views/messages/_controls.html.erb
<%= link_to 'Delete', message_path(message),
method: :delete,
data:{confirm: 'Are you sure', turbo_method: :delete},
class: 'message_delete-button text=themeColorSecondary hover:text-red-500'%>

app/views/messages/_form.html.erb
<%= form_with(
    model: message,
    id: "message_form",
    method: :post,
    data: { 
        controller: "reset-form",
        action: "turbo:submit-end->reset-form#clearInput"
    },
    class: "p-3 border-t border-borderColor1 flex items-center") do |form| %>

<%= form.text_field :body,
id: "chat-input",
class: "flex-grow p-3 rounded-md border border-borderColor1",
data: {
    reset_form_target: "input"
},
placeholder: "Type a Message . . ."%>
<%= form.button class: "ml-2 rounded-full bg-themeColorMain text-white w-10 h-10 flex justify-center items-center" do %>
 <!-- paper airplane icon -->
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-6 w-6">
    <path stoke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 1919 2-9-18-9 18 9-2zm0 0v-8"></path>
    </svg>
    <%end%>
<%end%>

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message) do%>
    <div class="message" data-user-id="<%=message.user.id%>">
        <div class="message_header flex justify-between text-textColorMain">
            <div>
                <div class="message_author">
                    <%= message.user.username %>
                </div>
                <div class="message_timestamp">
                    <%= message.created_at.strftime("%H:%M:%S")%>
                </div>
            </div>
            <%= turbo_frame_tag [dom_id(message), "controls"] do%>
                <% if display_control %>
                    <%= render partial: "messages/controls", locals:{ message: message}%>
                <%end%>
            <%end%>
        </div>
        <div class="message__body">
            <%=message.body %>
        </div>
</div>
<%end%>

app/views/pages/home.html.erb
<%= turbo_stream_from dom_id(current_user) %>
<div class="flex flex-col h-full bg-secondaryBgColor">
    <div class="flex flex-col h-full text-white">
        <h1 class="text-3xl font-bold text-center">Chatroom</h1>
        <p class="text-center">Welcome <%= current_user.username%>!</p>
    </div>
    <div id="chatbox" class="flex flex-col-reverse overflow-y-auto p-3 space-y-reverse">
        <%= render partial: "messages/chatbox", locals:{messages: @messages}%>
    </div>
    <%=render partial: "messages/form", locals:{message: @message}%>
</div>